CREATE TABLE IF NOT EXISTS plantilla_documentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo TEXT NOT NULL,
  nombre_archivo TEXT NOT NULL,
  ruta_storage TEXT NOT NULL,
  tamanio_bytes BIGINT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Permitir todo para el service_role key
CREATE POLICY "permitir_admin" 
ON plantilla_documentos
FOR ALL USING (true);
